Fixed Dnsdumpster Error and improved result
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd8413440d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 645, in enumerate
    token = self.get_csrftoken(resp)
  File "sublist3r.py", line 640, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
TypeError: expected string or buffer

Fixed this Error by using @hoseta method https://github.com/aboul3la/Sublist3r/issues/33#issuecomment-542613643